<a href="https://colab.research.google.com/github/Shabby78/Google_collab/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this n/b, we are going to cover some of the most important fundamentals concepts of tensors using tensorflow

More specifically , we are going to cover:
* Intro to tensors
* Getting information from tensors
* Manipulating the tensors
* Tensor & Numpy
* Using @tf.finction ( a way to speed up regular python fns)

## Introduction to Tensors


#### Creating tensors with 'tf.constant'

In [ ]:
 # Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.17.0


**Scalar**
A single number

In [ ]:
# Create Tensors  with tf.constant()- SCALAR
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Create the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

**Vector**
A number with direction (eg. wind speed and direction)

In [ ]:
# Create a Tensor with tf.constant()- VECTOR
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Create the number of dimensions of a tensor
vector.ndim

1

**Matrix**:
A 2-d array of numbers

In [ ]:
# Create a tensor for MATRIX(more than 1 dimension)
matrix=tf.constant([[7,8],
                   [8,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [8, 7]], dtype=int32)>

In [ ]:
# Create a number of dimension of this matrix
matrix.ndim

2

In [ ]:
# Create a another matrix
another_matrix= tf.constant([[10.,7.],
                             [7.,10.],
                             [7.,8.]],dtype=tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 7.,  8.]], dtype=float16)>

In [ ]:
# what's the number of dimension of the another_matrix
another_matrix.ndim

2

**Tensors**:
This is n-dimensional array of numbers  
 Where n can be any number , (0-dim tensor is a scalar, 1-d is a vector)






In [ ]:
# Lets create the tensors
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
# dimension of the "tensor"
tensor.ndim

3

**WHAT I HAVE CREATED SO FAR:**
 * Scalar: a single  number
 * vector: a numner with direction (eg, wind speed and direction)
 * Matrix: a 1-d array of numbers
 * Tensors: a n-dimensional array of numbers ( can be, 0-d scalar, 1-d vector, n-d somthing)

#### Creating tensors with 'tf.variable'

In [ ]:
# Create the same tensor with tf.variable() as previous as Vector
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0]=7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about we try .assign()
changeable_tensor[1].assign(7)
print(changeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>


In [ ]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0]
new_var = unchangeable_tensor[0].assign(7)
new_var

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

##### 🔑 **Note**: Rarely in practice will you need to decide whether to use 'tf.constant' of 'tf.Variable' to create tensors, as TensorFlow does for u. However, if in doubt ,use 'tf.constant' and change it later if needed.



### Creating Random Tensors
Random tensors are tensors of some abitrary size which contains random numbers

In [ ]:
# Create two random ( but the same) tensors
random_1=tf.random.Generator.from_seed(5)
random_1=random_1.normal(shape=(3,2))

random_2=tf.random.Generator.from_seed(5)
random_2=random_2.uniform(shape=(3,2))

random_1,random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.0278524 ,  0.27974114],
        [-0.01347923,  1.845181  ],
        [ 0.97061104, -1.0242516 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.567016  , 0.2077086 ],
        [0.18223882, 0.99883735],
        [0.36950588, 0.37927854]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle the tensor ( valuable for when you want to shuffel the data so the inheret order doesn't affect learning)
not_shuffled= tf.constant([[10,7],
                          [3,4],
                          [2,5]])
#not_shuffled, not_shuffled.ndim
## Shuffling our non-shuffled tensor
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [ ]:
## shuffle non- shuffled tensors
tf.random.set_seed(7)
tf.random.shuffle(not_shuffled,seed=7)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

##### 🛠️ **Exercise:** Read through the tensorflow doc about the "Random Seed Generation" : https://www.tensorflow.org/api_docs/python/tf/random/set_seed and pratice writing 5 random tensors and shuffle them.

> It looks like if i want to shuffle the tensors to be in the same order ,we got to use both global and operation level seed to do that

In [ ]:
# 1st - Neither Global or Operation level
Const_tf=tf.constant([[3,2],
                      [45,23],
                      [12,7]])
Const_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  2],
       [45, 23],
       [12,  7]], dtype=int32)>

In [ ]:
# 2nd - Operation_level set, not Global
tf.random.shuffle(Const_tf,seed=12)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12,  7],
       [45, 23],
       [ 3,  2]], dtype=int32)>

In [ ]:
# 3rd - Global is set, Operation-level not set
tf.random.set_seed(5)
tf.random.shuffle(Const_tf)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12,  7],
       [ 3,  2],
       [45, 23]], dtype=int32)>

In [ ]:
# 4th - Both is set, Global and Operational-level
tf. random.set_seed(7)
tf.random.shuffle(Const_tf,seed=7)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[45, 23],
       [ 3,  2],
       [12,  7]], dtype=int32)>

### Others ways to make Tensors

In [ ]:
# Create a tensor with all ones ( like numpy.ones)
tf.ones([7,7])

<tf.Tensor: shape=(7, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor with all Zeros
tf.zeros(shape=(7,7))

<tf.Tensor: shape=(7, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into Tensors
The main difference b/w NumPy arrays and tensors is that tensors runs on GPUs( much faster in numberical computing)

In [ ]:
# Turning numpy arrays into Tensors
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32) # create a numpy array between 1 and 25
numpy_A

# X= tf.constant(some_matrix) # capital for matrix or tensor
# y= tf.constant(Vector) # non-capital for Vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(numpy_A,shape=(2,4,3))
B=tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
2*4*3

24

In [ ]:
n_A=np.arange(1,50,dtype=np.int32)
T=tf.constant(n_A,shape=(7,7))
T

<tf.Tensor: shape=(7, 7), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]], dtype=int32)>

### Getting Information from Tensors

When dealing with tensors probably want to aware about all attribute:
* **Shape** - the length (no. of elemsnts) of each dimension of a tensor
* **Rank** - No. of tensor dimension
* **Axis or dimension** - a particular dimension of a tensor ,tensor[0],tensor[:,1]
* **Size** - Total no. of items in a tensor

In [ ]:
# Creating the rank 4 tensors (4 dimensions)
rank_4_tensor=tf.ones(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:

rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
print("DataType of every element: ",rank_4_tensor.dtype)
print("Number f dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ",rank_4_tensor.shape)
print("Element along 0 axis: ",rank_4_tensor.shape[0])
print("Element aling last axis:",rank_4_tensor.shape[-1])
print("Total number of tensor in every element", tf.size(rank_4_tensor))
print("Total number of tensor in every element", tf.size(rank_4_tensor).numpy())

DataType of every element:  <dtype: 'float32'>
Number f dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Element along 0 axis:  2
Element aling last axis: 5
Total number of tensor in every element tf.Tensor(120, shape=(), dtype=int32)
Total number of tensor in every element 120


### Indexing Tensors
Indexing tensors are just like python lists.

In [ ]:
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
# Get the fisrt 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [ ]:
# Get first element from each dimension from each index except the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1., 1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
# Creating a rank 2 tensor
rank_2_tensor=tf.constant([[2,3],
                          [5,5]])
rank_2_tensor, rank_2_tensor.ndim, rank_2_tensor.shape


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 3],
        [5, 5]], dtype=int32)>,
 2,
 TensorShape([2, 2]))

In [ ]:

# Get the last item of each row from rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [ ]:
# Add the extra dimension to rank 2 tensor
rank_3_tensor= rank_2_tensor[...,tf.newaxis]
rank_3_tensor, f'dimension of the tensor is:  {rank_3_tensor.ndim}'

(<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[2],
         [3]],
 
        [[5],
         [5]]], dtype=int32)>,
 'dimension of the tensor is:  3')

In [ ]:
# ALternate to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # '-1' means expand final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[5],
        [5]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [5, 5]]], dtype=int32)>

### Manipulating tensor (tensor operations)
**Basic Operation**

In [ ]:
# we can add values to the tensor by add operator
tensor=tf.constant([[10,7],[2,3]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [12, 13]], dtype=int32)>

In [ ]:
# original tensor is unchanged

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3]], dtype=int32)>

In [ ]:
# multiplication
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 20,  30]], dtype=int32)>

In [ ]:
# subtraction
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-8, -7]], dtype=int32)>

In [ ]:
# we can use tensorflow built in functions also
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 20,  30]], dtype=int32)>

In [ ]:
tf.add(tensor,45)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[55, 52],
       [47, 48]], dtype=int32)>

In [ ]:
tf.subtract(tensor,30)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-20, -23],
       [-28, -27]], dtype=int32)>

In [ ]:

# can also add math function to run this
tf.math.add(tensor,30)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 37],
       [32, 33]], dtype=int32)>

### Matrix Multiplication

In ML, matrix multiplication is one of the most imp. tensor operation

-To multiply one matrix to another we need todo the "DOT Product"
-Dot product: is where we multiply the matching members
-(1,2,3)*(7,9,11)=1*7 + 2*9 + 3*11 = 58

In [ ]:
# Matrix nultiplication of a tensor
tf.linalg.matmul(tensor,tensor) # linalg means Linear Algebra

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[114,  91],
       [ 26,  23]], dtype=int32)>

In [ ]:
# or we can also write it like this
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[114,  91],
       [ 26,  23]], dtype=int32)>

In [ ]:
#
t1=tf.constant([[1,2,5],
                [7,2,1],
                [3,3,3]])

t2=tf.constant([[3,5],
                [6,7],
                [1,8]])
tf.matmul(t1,t2)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:

# if we want to change the shape of the tensor
# We can do the same with Transpose
tf.reshape(t2,shape=(3,2)),tf.transpose(t2)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 6, 1],
        [5, 7, 8]], dtype=int32)>)

In [ ]:
tf.transpose(t2)
t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

##### The differnece b/w the TRANSPOSE & RESHAPE is transpose flips axis , where reshape shuffle in tensor around into shape you want

In [ ]:
t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [ ]:
# Try matrix multiplication with transppose
tf.matmul(t2,tf.transpose(t1))

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,3] [Op:MatMul] name: 

In [ ]:
# Practice the matmul function with random fucntion
rt1=tf.random.Generator.from_seed(42)
rt1=rt1.normal(shape=(2,3))

rt2= tf.random.Generator.from_seed(42)
rt2=rt2.normal(shape=(2,3))

rt2=tf.reshape(rt2,shape=(3,2))
tf.matmul(rt1,rt2)


📖 **Resources**: For matrix multiplication this is the resourse for best understaning of the matrix multiplication and here it is: https://www.mathsisfun.com/algebra/matrix-multiplying.html

#### **Dot Product:**
Matrix multiplication is alos refered as the dot product
* " tf.matmul()"
* " tf.tensordor()"

In [ ]:
# Perform dot product on X and Y (req. X & Y to be transposed)
X=tf.constant([[1,2,5],
                [7,2,1],
                [3,3,3]])

Y=tf.constant([[3,5],
                [6,7],
                [1,8]])

tf.tensordot(X,Y,axes=1) # we need axes to be mentioned in the tensordot function



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
x=tf.constant([[1,23],
               [2,3],
               [3,3]])
x
y= tf.constant([[1,2,3],
                [4,5,6]])
tf.tensordot(x,y,axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 93, 117, 141],
       [ 14,  19,  24],
       [ 15,  21,  27]], dtype=int32)>

Generally, when performing matrix multiplication on 2 tensors and one of the axes doesnot line up i will **transpose** ( rather than **reshape** ) one of the tensors to satisfy matrix multiplication rules.

### Changing the datatype of the tensor

In [ ]:
# create the new tensor with default dtype
B=tf.constant([2.5,4.5])
B.dtype

tf.float32

In [ ]:
C=tf.constant([7,10])
C.dtype

tf.int32

**Reduced Precision:**  Mixed precision is the use of both 16-bit and 32-bit floating-point types in a model during training to make it run faster and use less memory. By keeping certain parts of the model in the 32-bit types for numeric stability, the model will have a lower step time and train equally as well in terms of the evaluation metrics such as accuracy. This guide describes how to use the Keras mixed precision API to speed up your models. Using this API can improve performance by more than 3 times on modern GPUs, 60% on TPUs and more than 2 times on latest Intel CPUs.

In [ ]:
# Change from float32 ot float16 (reduced precision)
D=tf.cast(B,dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2.5, 4.5], dtype=float16)>

In [ ]:
# Change from int32 to float32
Aa=tf.constant([2,3])
a_cast=tf.cast(Aa,dtype=tf.float32)
a_cast, a_cast.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>,
 tf.float32)

### Tensor Aggregation
--> Aggregation tensor= condensing them from multiple values down to smaller amount of values

--> It refers to the process of reducing the dimensionality of the tensor by combinig its elements based on some operations

--> Aggregation in the context of tensor refers to the process of combining multiple tensor inputs into single output , often reducing its dimensonality.

In [ ]:
# Get the ABSOLUTE VALUES- changing the negative tensor values into positive tensor like [-2,-1]-->> [2,1]
d=tf.constant([-2,-1])
# get the absolute value
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 1], dtype=int32)>

Lets go through the following forms of aggregation:
* Get the Minimum
* Get the Maximum
* Get the mean of the tensor
* Sum if the tensor  

In [ ]:
# Creating the random tensor with values 0 to 100 of size 50
random1=tf.constant(np.random.randint(0,100,size=50))
random1

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 3, 51, 62, 44, 85, 45, 57, 36, 22, 36, 26, 31, 88, 50, 64,  1, 34,
       97, 93, 34, 55, 92, 50,  9,  5, 22, 37, 10, 82, 48, 93,  6, 36, 43,
       74, 36, 46, 60, 56, 22, 49, 62, 95, 55, 77, 96, 53, 36, 63, 21])>

In [ ]:
random2=tf.random.Generator.from_seed(5)
random2=random2.normal(shape=(3,2))
tf.abs(random2)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.0278524 , 0.27974114],
       [0.01347923, 1.845181  ],
       [0.97061104, 1.0242516 ]], dtype=float32)>

In [ ]:
random3=tf.constant(np.arange(0,100,dtype=np.int32))
#random2

random3=tf.constant(random3,shape=(4,25))
random3,random3.ndim

(<tf.Tensor: shape=(4, 25), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
         41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
         66, 67, 68, 69, 70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
         91, 92, 93, 94, 95, 96, 97, 98, 99]], dtype=int32)>,
 2)

In [ ]:
# find the minimum
tf.reduce_min(random1),tf.reduce_min(random2),tf.reduce_min(random3)

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-1.0242516>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>)

In [ ]:
# Find the Maximum
tf.reduce_max(random1),tf.reduce_max(random2),tf.reduce_max(random3)

(<tf.Tensor: shape=(), dtype=int64, numpy=97>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.845181>,
 <tf.Tensor: shape=(), dtype=int32, numpy=99>)

In [ ]:
# Find the mean
tf.reduce_mean(random1),tf.reduce_mean(random2),tf.reduce_mean(random3)

(<tf.Tensor: shape=(), dtype=int64, numpy=48>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.5142758>,
 <tf.Tensor: shape=(), dtype=int32, numpy=49>)

In [ ]:
# FInd the sum
tf.reduce_sum(random1),tf.reduce_sum(random2),tf.reduce_sum(random3)

(<tf.Tensor: shape=(), dtype=int64, numpy=2448>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.0856547>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4950>)

In [ ]:
# FInd the variance
# TO the variance of the tensor, we need to impoert the tensorflow_probability to run that
import tensorflow_probability as tfp
tfp.stats.variance(random1),tfp.stats.variance(random2),tfp.stats.variance(random3)

(<tf.Tensor: shape=(), dtype=int64, numpy=709>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.22845353, 1.3760715 ], dtype=float32)>,
 <tf.Tensor: shape=(25,), dtype=int32, numpy=
 array([781, 781, 781, 781, 781, 781, 781, 781, 781, 781, 781, 781, 781,
        781, 781, 781, 781, 781, 781, 781, 781, 781, 781, 781, 781],
       dtype=int32)>)

In [ ]:
# Find the standard deviaiton
tf.math.reduce_std(tf.cast(random1,dtype=tf.float32)),tf.math.reduce_std(tf.cast(random2,dtype=tf.float32)),tf.math.reduce_std(tf.cast(random3,dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=float32, numpy=26.618761>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9077361>,
 <tf.Tensor: shape=(), dtype=float32, numpy=28.86607>)

In [ ]:
# to finds the variance of the tensor without any useof stats we can also
tf.math.reduce_variance(tf.cast(random1,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=708.5584>

### Find the positional maximum and minimum (3-09-24)

In [ ]:
# Create a new tensor for finding thw positional max min
tf.random.set_seed(77)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.07212555, 0.5266396 , 0.72306037, 0.35061193, 0.8296379 ,
       0.11147892, 0.457646  , 0.16073549, 0.84786737, 0.96440816,
       0.31061685, 0.10325825, 0.8765378 , 0.7888309 , 0.39391422,
       0.464728  , 0.38612247, 0.5357307 , 0.3301475 , 0.22967815,
       0.17843282, 0.64866376, 0.35661578, 0.58480024, 0.9027157 ,
       0.70363975, 0.9455031 , 0.5759568 , 0.32488906, 0.93933237,
       0.18535316, 0.9726256 , 0.46691728, 0.6460202 , 0.7892866 ,
       0.6747252 , 0.8288157 , 0.05637586, 0.00927389, 0.5812448 ,
       0.96447814, 0.7342422 , 0.59657824, 0.876703  , 0.8870752 ,
       0.85794044, 0.47055292, 0.28132105, 0.6987431 , 0.0160569 ],
      dtype=float32)>

In [ ]:
# FInd the positional MAX
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=31>

In [ ]:
#Index  on our largest value posiiton
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9726256>

In [ ]:
# Find the max value
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9726256>

In [ ]:
# Check the equility
# Assert : if they are equal it do not throw any error, otherwise if we do not use it will show "true/false"
assert F[tf.argmax(F)]==tf.reduce_max(F)

In [ ]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=38>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009273887>

In [ ]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009273887>

### Squeezing the tensors (Removing all single dimensions)

In [ ]:
tf.random.set_seed(77)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G


<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.07212555, 0.5266396 , 0.72306037, 0.35061193, 0.8296379 ,
           0.11147892, 0.457646  , 0.16073549, 0.84786737, 0.96440816,
           0.31061685, 0.10325825, 0.8765378 , 0.7888309 , 0.39391422,
           0.464728  , 0.38612247, 0.5357307 , 0.3301475 , 0.22967815,
           0.17843282, 0.64866376, 0.35661578, 0.58480024, 0.9027157 ,
           0.70363975, 0.9455031 , 0.5759568 , 0.32488906, 0.93933237,
           0.18535316, 0.9726256 , 0.46691728, 0.6460202 , 0.7892866 ,
           0.6747252 , 0.8288157 , 0.05637586, 0.00927389, 0.5812448 ,
           0.96447814, 0.7342422 , 0.59657824, 0.876703  , 0.8870752 ,
           0.85794044, 0.47055292, 0.28132105, 0.6987431 , 0.0160569 ]]]]],
      dtype=float32)>

In [ ]:
G_squeezed=tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.07212555, 0.5266396 , 0.72306037, 0.35061193, 0.8296379 ,
        0.11147892, 0.457646  , 0.16073549, 0.84786737, 0.96440816,
        0.31061685, 0.10325825, 0.8765378 , 0.7888309 , 0.39391422,
        0.464728  , 0.38612247, 0.5357307 , 0.3301475 , 0.22967815,
        0.17843282, 0.64866376, 0.35661578, 0.58480024, 0.9027157 ,
        0.70363975, 0.9455031 , 0.5759568 , 0.32488906, 0.93933237,
        0.18535316, 0.9726256 , 0.46691728, 0.6460202 , 0.7892866 ,
        0.6747252 , 0.8288157 , 0.05637586, 0.00927389, 0.5812448 ,
        0.96447814, 0.7342422 , 0.59657824, 0.876703  , 0.8870752 ,
        0.85794044, 0.47055292, 0.28132105, 0.6987431 , 0.0160569 ],
       dtype=float32)>,
 TensorShape([50]))

### One-Hot Encoding

In [ ]:
# Create alist of indices
some_list=[0,1,2,3,7]
#One hot encoding
tf.one_hot(some_list,depth=8)


<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# FUN: Specify custom values for one hot encoding
tf.one_hot(some_list,depth=5,on_value="darth vader",off_value="anakin skywalker")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'darth vader', b'anakin skywalker', b'anakin skywalker',
        b'anakin skywalker', b'anakin skywalker'],
       [b'anakin skywalker', b'darth vader', b'anakin skywalker',
        b'anakin skywalker', b'anakin skywalker'],
       [b'anakin skywalker', b'anakin skywalker', b'darth vader',
        b'anakin skywalker', b'anakin skywalker'],
       [b'anakin skywalker', b'anakin skywalker', b'anakin skywalker',
        b'darth vader', b'anakin skywalker'],
       [b'anakin skywalker', b'anakin skywalker', b'anakin skywalker',
        b'anakin skywalker', b'anakin skywalker']], dtype=object)>

### Square , log, square root

In [ ]:
# Create a tensor
H=tf.constant(np.arange(1,10),shape=(3,3))
H

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [ ]:
# Find the Square of the tensor
tf.square(H)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])>

In [ ]:
# find the square root
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898],
       [2.6457512, 2.828427 , 3.       ]], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.       , 0.6931472, 1.0986123],
       [1.3862944, 1.609438 , 1.7917595],
       [1.9459102, 2.0794415, 2.1972246]], dtype=float32)>

### Tesors and Numpy
Tensors interacts beautifuly with numpy

🔑**Note:** One of the main difference between a tensorflow tensor and numpy array is that the tensor is faster because it can run on the GPU or TPU

In [ ]:
# create a tensor directly from numpy array
J=tf.constant(np.array([3.,4.,5.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 4., 5.])>

In [ ]:
# Convert tensor into numpy
np.array(J),type(np.array(J))

(array([3., 4., 5.]), numpy.ndarray)

In [ ]:
# Convert tensor J to numpy array
J.numpy(),type(J.numpy())

(array([3., 4., 5.]), numpy.ndarray)

In [ ]:
# Default types of each are slightly different
numpy_J=tf.constant(np.array([3.,4.4,5.5]))
tensor_J=tf.constant([3.4,3.4,6.6])
# check the datatype
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

### Finding Access to GPUs

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_logical_devices("GPU")

[LogicalDevice(name='/device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sat Sep  7 16:44:57 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P0              30W /  70W |    103MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

🔑**Note**: If you have access to CUDA-enabled GPU, Tensorflow will automatically use it whenever it is possible